# Generated by Django 5.1.1 on 2024-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_events_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=20)),
                ('dname', models.CharField(max_length=100)),
                ('dhod', models.CharField(max_length=100)),
                ('ddirector', models.CharField(max_length=100)),
                ('demail', models.CharField(max_length=100)),
                ('dcontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
    ]
