# Generated by Django 5.1.1 on 2024-09-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_departments_id_remove_events_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
