# Generated by Django 5.1.1 on 2024-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_delete_departments_delete_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('sponser_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('sponser_name', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('mode_of_transaction', models.CharField(blank=True, max_length=10, null=True)),
                ('ratings', models.DecimalField(blank=True, db_column='Ratings', decimal_places=0, max_digits=5, null=True)),
                ('contact', models.DecimalField(blank=True, db_column='Contact', decimal_places=0, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=10, null=True)),
            ],
            options={
                'db_table': 'sponsers',
                'managed': False,
            },
        ),
    ]
