# Generated by Django 5.1.1 on 2024-10-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_sponsers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsers',
        ),
    ]
