# Generated by Django 5.1.1 on 2024-10-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_delete_sponsers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False},
        ),
    ]
