# Generated by Django 5.1.1 on 2024-10-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
