# Generated by Django 5.1.1 on 2024-10-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_events_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('hod', models.CharField(blank=True, max_length=20, null=True)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('participant_rollno', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('participant_contactno', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
                ('participant_email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('participant_age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('participant_gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('sponser_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('sponser_name', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('mode_of_transaction', models.CharField(blank=True, max_length=10, null=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sponser_contactno', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'sponsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('vid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=100)),
                ('vblock', models.CharField(max_length=100)),
                ('vcapacity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('volunteer_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('volunteer_roll_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('volunteer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('volunteer_age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('volunteer_contact', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
                ('volunteer_email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'volunteers',
                'managed': False,
            },
        ),
    ]
