# Generated by Django 5.1.1 on 2024-10-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_department_participants_registration_sponsers_venue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Sponsers',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='Volunteers',
        ),
    ]
