# Generated by Django 5.1.1 on 2024-10-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_delete_participants_delete_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('vid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=100)),
                ('vblock', models.CharField(max_length=100)),
                ('vcapacity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
    ]
