# Generated by Django 5.1.1 on 2024-10-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('contest_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contest_email', models.CharField(blank=True, max_length=30, null=True)),
                ('coordinator', models.CharField(blank=True, max_length=30, null=True)),
                ('coordinator_contact', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'contests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_age', models.IntegerField(blank=True, null=True)),
                ('participant_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=40, null=True)),
                ('participant_contact', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
                ('participant_email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('volunteer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('volunteer_roll_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('volunteer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('volunteer_age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('volunteer_contact', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True)),
                ('volunteer_email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'volunteers',
                'managed': False,
            },
        ),
    ]
